export const AUTHENTICATION_CONFIG_PROVIDER = 'AUTHENTICATION.CONFIG';
export const USER_REPOSITORY = 'AUTHENTICATION.USER_REPOSITORY';
export const LOCAL_ACCOUNT_REPOSITORY =
  'AUTHENTICATION.LOCAL_ACCOUNT_REPOSITORY';
